- name: Print Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Run ls command
      command: ls /tmp
      register: ls_output

    - name: Display ls command output
      debug:
        var: ls_output.stdout_lines

    - name: Display ansible_ssh_private_key_file
      debug:
        var: ansible_ssh_private_key_file

    - name: Debug Print Machine Credential
      debug:
        var: ansible_machine_credential

    - name: Debug Print user
      debug:
        var: ansible_user

    - name: Debug Print user
      debug:
        var: ansible_password

- name: Test host
  hosts: demo_host
  become: yes
  become_method: sudo
 
  tasks:
    - name: Hello Message in demo_host with user and password
      debug:
        msg: "Hello World! I am using password"
        ansible_become_pass: "{{ your_password }}" 
        ansible_become_pass: "{{ your_username }}" 
      