- name: Print Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Run ls command
      command: ls /tmp
      register: ls_output

    - name: Display ls command output
      debug:
        var: ls_output.stdout_lines
    
    - name: Create key file
      copy:
        content: "{{ your_ssh_value }}"
        dest: "/tmp/remote_notes.txt"
    
    - name: Change SSH Private Key Permissions
      file:
        path: "/tmp/remote_notes.txt"
        mode: '0600'
      
    - name: Run ls command
      command: ls /tmp
      register: ls_output

    - name: Display ls command output
      debug:
        var: ls_output.stdout_lines
    
    - name: Create a text file with echo
      shell: cat /tmp/remote_notes.txt

    - name: Display ansible_ssh_private_key_file
      debug:
        var: ansible_ssh_private_key_file

    - name: Debug Print Machine Credential
      debug:
        var: ansible_machine_credential

    - name: Debug Print user
      debug:
        var: ansible_user

    - name: Debug Print user
      debug:
        msg: |
          ansible_user is {{ ansible_user | default('default_value') }}
          ansible_password is {{ ansible_password | default('default_value') }}
          ansible_ssh_user is {{ ansible_ssh_user | default('default_value') }}
          ansible_ssh_private_key_file is {{ ansible_ssh_private_key_file | default('default_value')}}

    - name: Debug AWX job
      debug:
        var: tower_job_id

- name: Test ssh host
  hosts: demo_host_ssh
  vars:
    ansible_ssh_user: "{{ your_ssh_username }}"
    ansible_ssh_private_key_file: "{{ your_ssh_path }}"
    not_defined: "{{ not_defined }}"
  tasks:
    - name: Hello Message in demo_host with ssh key
      debug:
        msg: "Hello World! I am using ssh key"
    
    - name: Create a text file with echo
      shell: echo "{{ tower_job_id }}" > ~/tmp/job-key.txt

    # - name: Test not_defined var when defined
    #   debug:
    #     var: not_defined
    #   when: not_defined is defined

    # - name: Test not_defined var when not defined
    #   debug:
    #     msg: |
    #       ansible_user is {{ ansible_user | default('default_value') }}
    #   debug:
    #     msg: | 
    #       not_defined variable is not defined
    #   when: not_defined is not defined
  
      
