- name: Print Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Run ls command
      command: ls
      register: ls_output

    - name: Display ls command output
      debug:
        var: ls_output.stdout_lines

    - name: Display ansible_ssh_private_key_file
      debug:
        var: ansible_ssh_private_key_file

    - name: Debug Print Machine Credential
      debug:
        var: ansible_machine_credential
