- name: Print Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Run ls command
      command: ls /tmp
      register: ls_output

    - name: Display ls command output
      debug:
        var: ls_output.stdout_lines

    - name: Display ansible_ssh_private_key_file
      debug:
        var: ansible_ssh_private_key_file

    - name: Debug Print Machine Credential
      debug:
        var: ansible_machine_credential

    - name: Debug Print user
      debug:
        var: ansible_user

    - name: Debug Print user
      debug:
        var: ansible_password

    - name: Debug AWX job
      debug:
        var: tower_job_id

- name: Test host
  hosts: demo_host
  vars:
    ansible_user: "{{ your_username }}" 
    ansible_password: "{{ your_password }}"
  tasks:
    - name: Hello Message in demo_host with user and password
      debug:
        msg: "Hello World! I am using password"
    
    - name: Create a text file with echo
      command: echo 'Tower Job ID: "{{ tower_job_id }}"' > /tmp/job.txt
      
