- name: Print Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

- name: Import playbook
  import_playbook: "print_ssh-key.yml"
  when:
  - your_ssh_username is defined
  - your_ssh_path is defined
  - your_ssh_value is defined
# - name: Test host
#   hosts: demo_host
#   vars:
#     ansible_user: "{{ your_username }}" 
#     ansible_password: "{{ your_password }}"
#   tasks:
#     - name: Hello Message in demo_host with user and password
#       debug:
#         msg: "Hello World! I am using password"
#       when: ansible_ssh_user is defined
    
#     - name: Create a text file with echo
#       shell: echo "{{ tower_job_id }}" > ~/tmp/job-user-pass.txt
#       when: ansible_ssh_user is defined
# - name: Test ssh host
#   hosts: demo_host_ssh
#   vars:
#     ansible_ssh_user: "{{ your_ssh_username }}"
#     ansible_ssh_private_key_file: "{{ your_ssh_path }}"
#     not_defined: "{{ not_defined }}"
#   tasks:
#     - name: Hello Message in demo_host with ssh key
#       debug:
#         msg: "Hello World! I am using ssh key"
    
#     - name: Create a text file with echo
#       shell: echo "{{ tower_job_id }}" > ~/tmp/job-key.txt

  
      
